spring:
  application:
    name: sbi-cloud
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        transmitSupplier-out-0:
          destination: transmit-queue-exchange
          content-type: application/json
        transmitConsumer-in-0:
          destination: transmit-queue-exchange
          content-type: application/json
          group: transmit-queue-group
          consumer:
            concurrency: 4

server:
  servlet:
    context-path: /sbicloud-queue
  port: 8082

management:
  security:
    enabled: false

#Swagger URL
# http://localhost:8082/sbicloud-queue/swagger-ui.html#/